services:
  pwnthemallagain:
    build: .
    platform: linux/amd64
    restart: on-failure
    ports:
      - 9992:9992
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
